name: Bug report
description: Something broken? Here's where to report it!
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        If this is a general question about the plugin or a point of confusion on a feature, please check [the wiki](https://github.com/kylechui/nvim-surround/wiki) before [opening a new discussion post](https://github.com/kylechui/nvim-surround/discussions/new).

  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: Have you updated the plugin to the latest version on `main` branch?
          required: true
        - label: Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
          required: true
        - label: Have you read through `:h nvim-surround` to see if there might be any relevant information there?
          required: true

  - type: textarea
    attributes:
      label: To reproduce
      description: |
        Give an example of a minimal sample buffer, cursor location, and keystroke sequence that generates the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: |
        Give what the expected buffer contents should be after the keystroke sequence.

  - type: textarea
    attributes:
      label: Actual behavior
      description: |
        Give what the actual buffer contents are after the keystroke sequence.

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Leave any additional information that you think might be relevant, or give your best shot at determining where the bug is coming from!
